FROM ubuntu:20.04

RUN apt-get update
RUN apt-get install openjdk-13-jdk -y
RUN apt-get install wget -y 
RUN apt-get install gnupg -y
RUN apt-get update
RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc |apt-key add -
RUN apt-get update
RUN apt-get install -y lsb-release
RUN apt-get update
RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |tee  /etc/apt/sources.list.d/pgdg.list
RUN apt -y update 
RUN apt -y install postgresql-12 postgresql-client-12
RUN apt-get install systemd -y 
RUN apt -y update 
EXPOSE 5432
RUN set -ex && apt-get install -y sudo
COPY com.cocentris.id.core.jar /home/com.cocentris.id.core.jar
COPY DBidcore.sh /home/DBidcore.sh
COPY idcore.sql /home/idcore.sql
COPY script.sh /home/script.sh
COPY ex.sh /home/ex.sh
RUN ./home/script.sh
RUN echo "listen_addresses='*'" >> /etc/postgresql/12/main/postgresql.conf
CMD ./home/ex.sh






